# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
