# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20170412_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 4, 13, 0, 56, 37, 959061, tzinfo=utc), verbose_name='Date')),
                ('survey', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey', verbose_name='Survey')),
            ],
        ),
    ]
