# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20170413_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='Default title', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
