# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20170413_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
    ]
