# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_auto_20170413_0439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankchoicepair',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='rankchoicepair',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='rankanswer',
            name='rank_choice_pairs',
        ),
        migrations.AddField(
            model_name='rankanswer',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.Choice', verbose_name='Choice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankanswer',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Ranking'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RankChoicePair',
        ),
    ]
