# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_auto_20170424_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='gender',
            field=models.CharField(choices=[('NDEF', 'Undefined'), ('MALE', 'Male'), ('FEMA', 'Female')], default='NDEF', max_length=4, verbose_name='Type'),
        ),
    ]
