# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_auto_20170503_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scale_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('STARS', 'Stars')], default='NORMAL', max_length=6, verbose_name='Rate type'),
        ),
    ]
