# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20170503_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('NDEF', 'Undefined'), ('MALE', 'Male'), ('FEMA', 'Female')], default='NDEF', max_length=4, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, verbose_name='Age')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Session', verbose_name='Session')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='gender',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Respondent', verbose_name='Author'),
        ),
    ]
