# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0020_auto_20170506_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='age',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Age'),
        ),
    ]
