# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 03:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_auto_20170506_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respondent',
            options={'verbose_name': 'Respondent', 'verbose_name_plural': 'Respondents'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Respondent', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='age',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Age'),
        ),
    ]
